arch: s390x
services:
  - docker
env:
  global:
    - TEST_DIR="$PWD"
    - TEST_SCRIPT="test.sh"
    - BUILD_DIR="$PWD/build/linux/"
    - REPO="quay.io/ibmz/elasticsearch"
    - TAG="$REPO:7.9.1"
before_script: 
  #- cd $TEST_DIR && chmod +x $TEST_SCRIPT
  - docker login quay.io -u $ROBOT -p $ROBOT_TOKEN
script: 
  - docker build $PWD/base/ --tag portainer/base
  - docker build $BUILD_DIR --tag $TAG
  #- cd $TEST_DIR && bash $TEST_SCRIPT 
after_script:
  - docker push $REPO
